import images from "./images";

const property = [
  {
    id: 13,
    name: "Riverside Haven",
    house_type: "House",
    img_src: images.asd1,
    address: "789 Riverside Dr, Waterside, NY",
    price: 2800,
    Bedroom: 4,
    Bathrooms: 3,
    location: "US",
    date: "1w",
    size: "6x7.5m",
  },
  {
    id: 14,
    name: "Maple Grove Townhome",
    house_type: "House",
    img_src: images.asd2,
    address: "123 Maple Lane, Suburbia, IL",
    price: 1950,
    Bedroom: 3,
    Bathrooms: 2,
    location: "CA",
    date: "1w",
    size: "5x6.5m",
  },
  {
    id: 15,
    name: "Oceanfront Retreat",
    house_type: "House",
    img_src: images.asd3,
    address: "456 Ocean Avenue, Seaside, CA",
    price: 3500,
    Bedroom: 5,
    Bathrooms: 4,
    location: "CA",
    date: "1w",
    size: "7x9m",
  },
  {
    id: 16,
    name: "Urban Loft",
    house_type: "Villa",
    img_src: images.asd4,
    address: "789 Downtown Blvd, Cityscape, TX",
    price: 2200,
    Bedroom: 2,
    Bathrooms: 1,
    location: "US",
    date: "1w",
    size: "4x5.5m",
  },
  {
    id: 17,
    name: "Forest Cabin",
    house_type: "Villa",
    img_src: images.asd5,
    address: "101 Woodland Rd, Wilderness, WA",
    price: 1800,
    Bedroom: 2,
    Bathrooms: 1,
    location: "DE",
    date: "1w",
    size: "4x6m",
  },
  {
    id: 18,
    name: "Skyline View Penthouse",
    house_type: "Flat",
    img_src: images.asd6,
    address: "123 Skyline Ave, Urban Heights, NY",
    price: 6000,
    Bedroom: 3,
    Bathrooms: 3,
    location: "CA",
    date: "1m",
    size: "7.5x10m",
  },
  {
    id: 19,
    name: "Garden Oasis",
    house_type: "House",
    img_src: images.asd7,
    address: "456 Blossom Lane, Green Valley, CA",
    price: 3200,
    Bedroom: 4,
    Bathrooms: 2,
    location: "CA",
    date: "1m",
    size: "6x7m",
  },
  {
    id: 20,
    name: "Historic Brownstone",
    house_type: "Flat",
    img_src: images.asd8,
    address: "789 Heritage Street, Heritage District, MA",
    price: 2800,
    Bedroom: 3,
    Bathrooms: 2,
    location: "US",
    date: "1m",
    size: "5x6m",
  },
  {
    id: 21,
    name: "Lakefront Cottage",
    house_type: "Flat",
    img_src: images.asd9,
    address: "101 Lakeside Rd, Lakeshore, MI",
    price: 2500,
    Bedroom: 2,
    Bathrooms: 1,
    location: "US",
    date: "1m",
    size: "4x5m",
  },
  {
    id: 22,
    name: "Modern Heights",
    house_type: "Flat",
    img_src: images.asd10,
    address: "123 Modern St, Urban District, CA",
    price: 3200,
    Bedroom: 2,
    Bathrooms: 2,
    location: "US",
    date: "now",
    size: "4.5x6.5m",
  },
];

export default { property };
